FROM ubuntu:18.04


RUN apt update
RUN apt install -y papi-tools
RUN apt install -y libpapi-dev

RUN apt install -y python3-pip

RUN apt install -y libgfortran4


RUN pip3 install psutil
RUN pip3 install tcp_latency



